同步改动

diff --git a/CustomFiles/Depends/profile b/CustomFiles/Depends/profile
--- a/CustomFiles/Depends/profile
+++ b/CustomFiles/Depends/profile
@@ -1,34 +1,34 @@
 Sysinfo() {
-	[ -f /etc/openwrt_info ] && source /etc/openwrt_info > /dev/null 2>&1
-	export Target=${DEFAULT_Device}
-	[ -n "${CURRENT_Version}" ] && export Version="${CURRENT_Version}" || Version=Unknown
-	[ -z "${Target}" ] && export Target=$(jsonfilter -e '@.model.id' < /etc/board.json | tr ',' '_')
-	export IP_Address=$(ifconfig -a | grep inet | grep -v 127.0.0.1 | grep -v inet6 | awk '{print $2}' | tr -d "addr:" | awk 'NR==1')
-	export CoreMark=$([ -f /etc/bench.log ] && egrep -o "[0-9]+" /etc/bench.log | awk 'NR==1')
-	export Startup=$(awk '{a=$1/86400;b=($1%86400)/3600;c=($1%3600)/60} {printf("%d 天 %d 小时 %d 分钟\n",a,b,c)}' /proc/uptime)
-	export Overlay_Available="$(df -h | grep ":/overlay" | awk '{print $4}' | awk 'NR==1')"
-	export TEMP=$(sensors 2>/dev/null | grep 'Core 0' | awk '{print $3}')
-	echo -e "\n           设备名称:		${Yellow}$(uname -n) / ${Target}${White}"
+	source /etc/AutoBuild/Default_Variable > /dev/null 2>&1
+	source /etc/AutoBuild/Custom_Variable > /dev/null 2>&1
+	[ -z "${CURRENT_Version}" ] && CURRENT_Version=未知
+	[ -z "${TARGET_PROFILE}" ] && local TARGET_PROFILE=$(jsonfilter -e '@.model.id' < /etc/board.json | tr ',' '_')
+	local IP_Address=$(ifconfig -a | grep inet | grep -v 127.0.0.1 | grep -v inet6 | awk '{print $2}' | tr -d "addr:" | awk 'NR==1')
+	local CoreMark=$([ -f /etc/bench.log ] && egrep -o "[0-9]+" /etc/bench.log | awk 'NR==1')
+	local Startup=$(awk '{a=$1/86400;b=($1%86400)/3600;c=($1%3600)/60} {printf("%d 天 %d 小时 %d 分钟\n",a,b,c)}' /proc/uptime)
+	local Overlay_Available="$(df -h | grep ":/overlay" | awk '{print $4}' | awk 'NR==1')"
+	local TEMP=$(sensors 2>/dev/null | grep 'Core 0' | awk '{print $3}')
+	echo -e "\n           设备名称:		${Yellow}$(uname -n) / ${TARGET_PROFILE}${White}"
 	[ -n "${TEMP}" ] && echo "           核心温度:		${TEMP}"
 	echo "           内核版本:		$(uname -rs)"
-	echo -e "           固件版本:		${Skyb}${Version}${White}"
+	echo -e "           固件版本:		${Skyb}${CURRENT_Version}${White}"
 	echo "           IP 地址 : 		${IP_Address}"
 	echo "           可用空间:		${Overlay_Available}"
-	echo "           运行时间: 		${Startup}"
 	[ -n "${CoreMark}" ] && echo "           性能得分:		${CoreMark}"
+	echo "           运行时间: 		${Startup}"
 	echo ""
 }
 
-White="\e[0m"
-Yellow="\e[33m"
-Red="\e[31m"
-Blue="\e[34m"
-Skyb="\e[36m"
+export White="\e[0m"
+export Yellow="\e[33m"
+export Red="\e[31m"
+export Blue="\e[34m"
+export Skyb="\e[36m"
 
 clear
 [ -e /tmp/.failsafe ] && export FAILSAFE=1
 [ -f /etc/banner ] && {
-	echo -e "$Blue"
+	echo -e "$Skyb"
 	cat /etc/banner
 	echo -e "$White"
 }
@@ -64,10 +64,27 @@ esac
 	unset FILE
 }
 
+service() {
+	[ -f "/etc/init.d/$1" ] || {
+		echo -e "${Red}service "'"'"$1"'"'" not found, the following services are available:${White}\n"
+		ls "/etc/init.d"
+		return 1
+	}
+	/etc/init.d/$@
+}
+
 Sysinfo
+alias reload='clear && /etc/profile'
 alias autoupdate='bash /bin/AutoUpdate.sh'
-alias AutoUpdate='bash /bin/AutoUpdate.sh'
-alias Tools='bash /bin/AutoBuild*.sh'
-alias tools='bash /bin/AutoBuild*.sh'
-alias coremarkd='bash /etc/coremark.sh'
+alias tools='bash /bin/AutoBuild_Tools.sh'
+alias run_coremark='bash /etc/coremark.sh'
 alias shutdown='sync && poweroff'
+alias ls='ls --color=auto'
+alias ll='ls -alF'
+alias la='ls -A'
+alias l='ls -CF'
+alias grep='grep --color=auto'
+alias egrep='egrep --color=auto'
+alias cls='clear'
+alias dh='df -h'
+alias ramfree='sync && echo 3 > /proc/sys/vm/drop_caches'
