合并改动

diff --git a/.github/workflows/AutoBuild-Common.yml b/.github/workflows/AutoBuild-Common.yml
--- a/.github/workflows/AutoBuild-Common.yml
+++ b/.github/workflows/AutoBuild-Common.yml
@@ -6,30 +6,26 @@
 # Modify: Hyy2001X
 #=======================================================
 
-name: AutoBuild-x86_64
+name: AutoBuild-Common
 
 on:
   repository_dispatch:
   workflow_dispatch:
     inputs:
       ssh:
-        description: 'SSH 连接到 Actions [可选]'
+        description: 'SSH 连接到 Actions'
         required: true
         default: 'false'
+      target_name:
+        description: '设备名称 [必选]'
+        default: ''
       ip_addr:
         description: '固件 IP 地址 [可选]'
         default: ''
 
-#  schedule:
-#    - cron: 0 11 * * *
-
-#  watch:
-#    types: [started]
-
 env:
   REPO_URL: https://github.com/coolsnowwolf/lede
   REPO_BRANCH: master
-  CONFIG_FILE: x86_64
   DIY_SCRIPT: Scripts/AutoBuild_DiyScript.sh
   FUNCTION_SCRIPT: Scripts/AutoBuild_Function.sh
   UPLOAD_RELEASE: true
@@ -51,6 +47,18 @@ jobs:
       env:
         DEBIAN_FRONTEND: noninteractive
       run: |
+        [[ -n "${{ github.event.inputs.target_name }}" ]] && {
+            echo "设备名称: ${{ github.event.inputs.target_name }}"
+        } || {
+            echo "[ERROR] 未输入设备名称!"
+            exit 1
+        }
+        [ -f "$GITHUB_WORKSPACE/Configs/${{ github.event.inputs.target_name }}" ] && {
+            echo "已检测到 [${{ github.event.inputs.target_name }}] 设备配置文件"
+        } || {
+            echo "[ERROR] 未检测到设备对应的 [${{ github.event.inputs.target_name }}] 的配置文件!"
+            exit 1
+        }
         sudo -E apt-get update
         sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
         sudo timedatectl set-timezone "Asia/Shanghai"
@@ -78,10 +86,7 @@ jobs:
       run: |
         git clone -b $REPO_BRANCH $REPO_URL openwrt
         ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
-        [ -f Configs/$CONFIG_FILE ] && cp Configs/$CONFIG_FILE openwrt/.config || {
-            echo "未检测到该设备的 $CONFIG_FILE 配置文件!"
-            exit 1
-        }
+        cp -a Configs/${{ github.event.inputs.target_name }} openwrt/.config
         cd openwrt
         ./scripts/feeds update -a
         ./scripts/feeds install -a
@@ -105,7 +110,7 @@ jobs:
 
     - name: Preload and Compile the Openwrt
       run: |
-        cp Configs/$CONFIG_FILE openwrt/.config
+        cp Configs/${{ github.event.inputs.target_name }} openwrt/.config
         cd openwrt
         ./scripts/feeds install -a
         make defconfig
